[tool.coverage.report]
omit = [
        "**/__init__.py",
        "stabl.py",
        "**/tests/**"
]
fail_under = 90

[tool.coverage.run]
branch = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing"